# Generated by Django 5.2.1 on 2025-05-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Objetivo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Objetivo Académico',
                'verbose_name_plural': 'Objetivos Académicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], help_text='Mes (1=Enero, 12=Diciembre)', primary_key=True, serialize=False, verbose_name='Número de Mes')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SGCObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Objetivo SGC')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción SGC')),
            ],
            options={
                'verbose_name': 'Objetivo SGC',
                'verbose_name_plural': 'Objetivos SGC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='El número oficial (1-68) que identifica este KPI.', unique=True, verbose_name='Número de KPI')),
                ('name', models.CharField(help_text='El nombre corto o título del KPI.', max_length=500, verbose_name='Nombre Corto / Título')),
                ('description', models.TextField(blank=True, help_text='Descripción explicando el KPI, su propósito y método de cálculo.', null=True, verbose_name='Descripción Detallada')),
                ('shown_to_board', models.BooleanField(default=False, verbose_name='Mostrar a la Junta Directiva')),
                ('powerbi_url_token', models.CharField(blank=True, help_text='Solo el ID/Token de embed para Power BI (ej: eyJrI...). Si pega la URL completa, se intentará extraer el token.', max_length=500, null=True, verbose_name='Power BI Embed ID/Token')),
                ('local_dash_url', models.CharField(blank=True, help_text='Ruta relativa (ej: /dashboard/kpi1) o URL completa para dashboards no Power BI.', max_length=200, null=True, verbose_name='URL de Dashboard Local/Alternativo')),
                ('academic_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='indicator_manager.academicobjective', verbose_name='Objetivo Académico Relacionado')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Persona responsable de la revisión y reporte del KPI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_kpis', to=settings.AUTH_USER_MODEL, verbose_name='Persona Responsable')),
                ('review_months', models.ManyToManyField(blank=True, help_text='Seleccione los meses en que este KPI debe ser revisado/reportado.', to='indicator_manager.month', verbose_name='Meses de Revisión')),
                ('sgc_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='indicator_manager.sgcobjective', verbose_name='Objetivo SGC Relacionado')),
            ],
            options={
                'verbose_name': 'Indicador (KPI)',
                'verbose_name_plural': 'Indicadores (KPIs)',
                'ordering': ['number'],
            },
        ),
    ]
