# Generated by Django 5.2.1 on 2025-05-26 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='indicator',
            name='external_file_url',
            field=models.URLField(blank=True, help_text='URL directa a una imagen o documento relevante para el KPI.', max_length=1024, null=True, verbose_name='URL de Archivo Externo (Imagen/Documento)'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, help_text='Personas responsables de la revisión y reporte del KPI.', related_name='responsible_kpis', to=settings.AUTH_USER_MODEL, verbose_name='Personas Responsables'),
        ),
    ]
