# Generated by Django 5.2.1 on 2025-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0002_remove_indicator_responsible_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='data_ingestion_model_name',
            field=models.CharField(blank=True, help_text="Nombre de la clase del modelo Django (ej: 'AttendanceData') donde se ingestarían los datos para este KPI.", max_length=100, null=True, verbose_name='Modelo Destino para Datos'),
        ),
    ]
