# Generated by Django 5.2.1 on 2025-05-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0003_indicator_data_ingestion_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('action_type', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado')], max_length=10, verbose_name='Tipo de Acción')),
                ('changed_data', models.JSONField(blank=True, null=True, verbose_name='Datos Modificados')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='indicator_manager.indicator', verbose_name='Indicador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Cambio de Indicador',
                'verbose_name_plural': 'Registros de Cambios de Indicadores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
