# Generated by Django 5.2.1 on 2025-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0004_indicatorchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='data_format_instructions',
            field=models.TextField(blank=True, help_text='Describa el formato esperado del archivo a subir (columnas, tipos de datos, etc.) para la ingesta de datos.', null=True, verbose_name='Instrucciones de Formato de Datos'),
        ),
    ]
