# Generated by Django 5.2.1 on 2025-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0006_raatdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorchangelog',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado')], max_length=15, verbose_name='Tipo de Acción'),
        ),
    ]
