# Generated by Django 5.2.1 on 2025-06-08 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_manager', '0007_alter_indicatorchangelog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Correo electrónico al que se envía la invitación. Debe ser único.', max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='¿Ha sido usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Invitación de Registro',
                'verbose_name_plural': 'Invitaciones de Registro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='indicatorchangelog',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('BULK_UPLOADED', 'Carga Masiva'), ('DELETED', 'Eliminado')], max_length=15, verbose_name='Tipo de Acción'),
        ),
    ]
